[package]
name = "lfsr-fibo"
version = "0.1.0"
edition = "2024"
authors = ["acmo0"]
license = "MIT OR Apache-2.0"
description = "Efficient pure Rust implemention of LFSR using Fibonacci representation."
readme = "README.md"
repository = "https://github.com/acmo0/lfsr-fibo.git"

[dependencies]
